### ISSUE TITLE
Backup Dropbox failing? Even on v2 api?

### ISSUE THREAD

**Issue by jonchui** [einaregilsson/MyLife#14] opened 2018-11-25 08:28 UTC
I’m getting this error in my emails:

```
Failed to backup posts and images to dropbox: Traceback (most recent call  
last):

File "/base/data/home/apps/s~jonchuislife/20171011t222458.404746098147759290/handlers/dropbox.py",  
line 39, in get
     result = self.put_file(settings.dropbox_access_token, 'MyLife.txt',  
post_text.getvalue().encode('utf-8'))

File "/base/data/home/apps/s~jonchuislife/20171011t222458.404746098147759290/handlers/dropbox.py",  
line 142, in put_file
     headers=headers

File "/base/alloc/tmpfs/dynamic_runtimes/python27g/3b44e98ed7fbb86b/python27/python27_lib/versions/1/google/appengine/api/urlfetch.py",  
line 293, in fetch
     return rpc.get_result()

File "/base/alloc/tmpfs/dynamic_runtimes/python27g/3b44e98ed7fbb86b/python27/python27_lib/versions/1/google/appengine/api/apiproxy_stub_map.py",  
line 615, in get_result
     return self.__get_result_hook(self)

File "/base/alloc/tmpfs/dynamic_runtimes/python27g/3b44e98ed7fbb86b/python27/python27_lib/versions/1/google/appengine/api/urlfetch.py",  
line 433, in _get_fetch_result
     'Connection closed unexpectedly by server at URL: ' + url)
ConnectionClosedError: Connection closed unexpectedly by server at URL:  
https://content.dropboxapi.com/2/files/upload
```

**Comment by einaregilsson** [comment] 2018-11-25 13:02
Is this happening every night? I've gotten this message a few times, but like maybe 10 times in 2 years or something.

**Comment by jonchui** [comment] 2018-11-26 02:46
It used to be infrequent, but now is much more frequent, i have 73.7% of my 15 GB dropbox full, so i don't think it's a space issue

here's a search:

![image](https://user-images.githubusercontent.com/204868/48990180-81202a00-f0d1-11e8-8b9b-bbd2ae70b15d.png)

**Comment by jonchui** [comment] 2018-11-26 02:59
Upon further investigation, when i run to the url `[domain]/backup/dropbox` to run the backup, it seems to work, and this appears on the screen:

```
Backing up 251 posts to Dropbox
Backed up posts. Revision: c82edaa2e4
Fetching Dropbox file list
Got 81 files from Dropbox
Fetching images...
Total images in MyLife: 80

Files not backed up: 



Files marked as backed up, but not in Dropbox: 


Found 0 images that need to be backed up in Dropbox
Finished backup successfully
```

**Comment by einaregilsson** [comment] 2018-11-26 10:23
That is pretty frequent, but I've never been able to reproduce these errors. I guess it must be a Dropbox thing, I searched for similar errors and all I found was some forum post where a Dropbox employee told someone to just retry in this case since errors like that could always happen. I should probably add 1 or 2 retries before sending the error message at some point.

**Comment by einaregilsson** [comment] 2020-01-09 08:24
Closing this, have gotten no further reports.

**Closed as completed by einaregilsson** 2020-01-09 08:24 UTC
